version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart_society_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_society
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: